language: scala

scala:
- 2.12.2
- 2.11.11

jdk:
- oraclejdk8

install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install

env:
  global:
    JSENV=node

script:
  - sbt ++$TRAVIS_SCALA_VERSION testDev testProd


deploy:
  provider: script
  script:
  - /bin/bash "$TRAVIS_BUILD_DIR/.travis.credentials.sh" && sbt ++$TRAVIS_SCALA_VERSION publish
  on:
    tags: true

env:
  global:
  # travis encrypt BINTRAY_USER=xxx
  - secure: "bSZE3HVkVBI2lTni07vla1wzv4sZ01b9n7edaZHpkQCmCqVqz49/QOCGOhF90vKTpBF3grSwMTz2ZlzxwydxJf3WlY5MxTqtpXbwQRPFcd59TLljBh5gAIApOs7T32Lv7kJRFHoYY8BgOJeGRRU7ZShIjG/pe/uMO/wbttDC5AzNs8Aln4HV+Z79CBfqkM1ZTx7A30urZ8qzM/ZWZZO663+eIP5FL3eCRPcjIDJnpGKlQyXwpTxwl2fcD8B7XXHDTVALHciHKQPrfFTOOuthOUuCEw7GVchX8XvGu8gbX1g7mh6uGYrXsx8UtpFx4POUxBoqYOXyQe5UY8b9JksdbnsAumEcDEyrcvXO1b5gtgMEPxjzK+X9hVE2MuSHLcdV4LVdJyt1sN19hFCs/ZWBF6PA+1+vRAsuf7g8xYY2tcrePmDby7BiYi6Z685HEPbuTCbq594XRdkyzgoj29jyNZCrTtDR72I/UIMcKEWFyP7maPd0x/K3p/irH0/Q/cjM/zOkfnHhpTkOfxPARny23zMdqR2r40+YjE3F5zNtvZU/JsTUwwTGYw8Ba3NEiXCaxsP/aEXGYAx5ObyOI2A/1+kMgMNO+uVIGobweKn4vkN1PkmkEhtxjY0SvS+jKfK8awFOUwb51A5FIVZdGksvl/HIYWvZ7nvVRjV9kEOjFxI="
  # travis encrypt BINTRAY_PASSWORD=xxx
  - secure: "zEv31AG+moXvj6hf25a5GZZf4vCtW95Ju33HObYEvHbZlikH92PXUD4YJWZvZKrVBe8x1UJyV+5XYNA1rg8RhMkpt7tjjvMDdUzD3MW9V9Paim73E1IPLd19WrYfBk/yK0MEgeI7+0ySptADVaYf3vCtPViWF+aLEzG0b+jorNKfyS2s0600+yhk1HJ0bfMKJChEqeILE9W5FgNHLn797SBFiQZRnr78ZTu3sIoadN/ylW6TONyG6k8PoK86Qzn+k7rYXFOoBEnQEBWUCdrNPlucQSows+R1gqYEcuC8zWQHtoAHQ/K5LnJuFULXomXLobAh884545+AxgPnfIH9wKwBCkxzjFtw4ewJ+hylD3OxHFcacC/X87EBqK5bpXX3LnBOZD/LY48pGrzyAWSrxs728jWhf9GErcNILL6UFGUipPxesNf22vUTeEeZswSOu5hNsmyJBKuVrEOuIS6F7VsYY4AM08k5duCGJLEf+a47xmGGfHQU/3CSWDJU/Sj9s3HRLzVNVFVFhyniDv4pDZsc8OIZKGGe6Wkq9n7l/v1Lmpw63hjtGskDLgXgC/BgDJcm+KmCHtFK6hMiWKDBxQt+k7G4Bk5tP4IBMy5LBncuQgaclArkXMIMiTzmjsSSKO8DOtyPBEO51VCLHooqYjsA0iHTXT4oBOO0lw79Bp8="

